### ISSUE TITLE
Lua runtime error when trying to simulate

### ISSUE THREAD

**Issue by Matheus3007** [filRocha/rosiChallenge-sbai2019#3]
Whenever I try to run the simulation related to the ROSI challenge, vrep never really establishes communication with ROS, so I'm not able to command the robot, instead I only get a runtime error (see bellow)

![ROSIRuntimeError](https://user-images.githubusercontent.com/53058455/61483367-0a42e480-a973-11e9-9ec0-0c0700b76328.png)

And if I try to take a look at what's going on with Rqt_graph, no nodes seem connected:

![Rqt_graphOut](https://user-images.githubusercontent.com/53058455/61483485-3fe7cd80-a973-11e9-94f6-49c9827ccdac.png)

I don't understand what's the issue here, since I've tried following the installation procedures countless times, and I'm positive that there's nothing wrong on that part of things, roscore is also running normally, I even checked to see if the issue was over there, so I came here as some kind of last resort, cause I just have no clue on how to make this work anymore.

**Comment by filRocha** [comment]
Hi, Matheus. Thank you for your post.

ROS master needs to be running before V-REP is initialized; otherwise, it won't be able to find the core.
Adittionally, if you shut down `roscore` while V-REP is running, you'll need to also restart the simulator to establish the connection.

Check if you are performing correctly those steps.
Also, see if you can find this message on V-REP initialization:

![image](https://user-images.githubusercontent.com/39299876/61543462-ebe3f400-aa19-11e9-8936-12b80cf2a904.png)

Please let me know if the problem continues.

Regards.

**Comment by filgusto** [comment]
Hi, Matheus. Thank you for your post.

ROS master needs to be running before V-REP is initialized; otherwise, it won't be able to find the core.
Adittionally, if you shut down roscore while V-REP is running, you'll need to also restart the simulator to establish the connection.

Check if you are performing correctly those steps.
Also, see if you can find this message on V-REP initialization:

![image](https://user-images.githubusercontent.com/39299876/61543725-6876d280-aa1a-11e9-8025-7d834830a795.png)

Please let me know if the problem continues.

Regards.

**Comment by Matheus3007** [comment]
I checked if I was running ROS master and V-REP in the correct order as you recommended me to, but unfortunately that was not the issue. Even though I ran roscore before starting V-REP, and left it running as I tried to run the simulation, the error kept appearing.

Also, I was able to find the ROS interface plugin message during the V-REP startup, and it seems to be loading just as it's supposed to:

![RosInterfacePluginOk](https://user-images.githubusercontent.com/53058455/61548298-ca880580-aa23-11e9-845e-e650d852909c.png)

(By the way, thanks for the quick reply!)

**Comment by filgusto** [comment]
Ok. I have just seen a small portion of your LUA log on the image you've sent and it looks like the custom ROSI ROS messages were not correctly incorporated to the `libv_repExtRosInterface.so`.
Considering the manual installation instructions of the challenge repository's README.md, be sure if the steps from 10 and on are well implemented. 
If the problem persists, please send here your LUA error log.

**Comment by Matheus3007** [comment]
Well, steps from 10 and on were done properly for sure, I just checked them, and to be sure of it I ran a small test to see if the ROS/V-REP interface was the problem, so I opened up a new scene with a script that published the simulation time to ROS, and it ran alright:

![ROSWorkingAlright](https://user-images.githubusercontent.com/53058455/61578831-0d54e680-aad3-11e9-857c-db9454556bf2.png)

This experiment lead me to believe that the problem has something to do with the rosi script itself, not the V-REP/ROS interface, since it doesn't make sense to me that the interface would fail only when trying to run the challenge scenario (I understand I may be wrong here, I'm really not familiar with LUA or V-REP)

Anyway, here's the LUA error log as you asked:
[LuaErrorLog.txt](https://github.com/filRocha/rosiChallenge-sbai2019/files/3413619/LuaErrorLog.txt)

Thanks for the help! :)

**Comment by Matheus3007** [comment]
Hello again! I'm closing this thread now. I was discussing the issue with my friend @TheoFabris and we managed to figure out a solution, which was simply replacing my libv_repExtRosInterface.so file with his, since he thought the problem was over there because it's virtually one of the only connections between ROS and V-REP. 
After replacing my file, that for some reason wasn't properly built, with his, everything started working as it should.
We haven't figured out exactly what the issue was, but there's the solution. Probably something wrong happend during steps 10 and on, just as you said :)!

Thanks for helping me through this issue!

**Comment by Matheus3007** [comment]
Hello again! I'm closing this thread now. I was discussing the issue with my friend @TheoFabris and we managed to figure out a solution, which was simply replacing my libv_repExtRosInterface.so file with his, since he thought the problem was over there because it's virtually one of the only connections between ROS and V-REP.
After replacing my file, that for some reason wasn't properly built, with his, everything started working as it should.
We haven't figured out exactly what the issue was, but there's the solution. Probably something wrong happend during steps 10 and on, just as you said :)!

Thanks for helping me through this issue!
